/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiCrmRouteImport } from './routes/api/crm'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmRoute = ApiCrmRouteImport.update({
  id: '/api/crm',
  path: '/api/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/crm': typeof CrmRoute
  '/estimator': typeof EstimatorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/crm': typeof ApiCrmRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/track': typeof ApiTrackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/crm': typeof CrmRoute
  '/estimator': typeof EstimatorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/crm': typeof ApiCrmRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/track': typeof ApiTrackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/crm': typeof CrmRoute
  '/estimator': typeof EstimatorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/crm': typeof ApiCrmRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/track': typeof ApiTrackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/crm'
    | '/estimator'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/crm'
    | '/api/leads'
    | '/api/track'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/crm'
    | '/estimator'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/crm'
    | '/api/leads'
    | '/api/track'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/crm'
    | '/estimator'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/crm'
    | '/api/leads'
    | '/api/track'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CrmRoute: typeof CrmRoute
  EstimatorRoute: typeof EstimatorRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiCrmRoute: typeof ApiCrmRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiTrackRoute: typeof ApiTrackRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm': {
      id: '/api/crm'
      path: '/api/crm'
      fullPath: '/api/crm'
      preLoaderRoute: typeof ApiCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CrmRoute: CrmRoute,
  EstimatorRoute: EstimatorRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiCrmRoute: ApiCrmRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiTrackRoute: ApiTrackRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
